repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  ### linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
      - id: ruff
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  ### type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy

  ### ensure conventional commits are used
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [ pre-push ]

  ### security for github actions
  - repo: https://github.com/woodruffw/zizmor
    rev: v0.8.0
    hooks:
    - id: zizmor
